export const traces = [
  {
    "id": "trace_001",
    "input": "What can I make with chicken and rice?",
    "output": "## Chicken Fried Rice\n\nA quick and satisfying one-pan meal that transforms leftover rice into a delicious dish with tender chicken and vegetables.\n\n### Ingredients\n* 2 cups cooked rice (preferably day-old)\n* 1 lb chicken breast, diced\n* 2 eggs, beaten\n* 1 cup mixed vegetables (peas, carrots, corn)\n* 3 cloves garlic, minced\n* 2 tbsp soy sauce\n* 1 tbsp sesame oil\n* 2 tbsp vegetable oil\n* 2 green onions, sliced\n* Salt and pepper to taste\n\n### Instructions\n1. Heat 1 tbsp vegetable oil in a large wok or skillet over medium-high heat.\n2. Add diced chicken and cook until golden brown and cooked through, about 6-8 minutes.\n3. Push chicken to one side of the pan and add beaten eggs to the other side.\n4. Scramble the eggs, then mix with the chicken.\n5. Add garlic and mixed vegetables, stir-fry for 2-3 minutes.\n6. Add the rice, breaking up any clumps, and stir to combine.\n7. Pour soy sauce and sesame oil over the rice, toss to coat evenly.\n8. Cook for 2-3 more minutes until heated through.\n9. Garnish with green onions and serve hot.\n\n### Tips\n* Day-old rice works best as it's less sticky and fries better\n* Feel free to add other vegetables like bell peppers or broccoli"
  },
  {
    "id": "trace_002",
    "input": "I need a vegan dessert recipe",
    "output": "## Chocolate Avocado Mousse\n\nA rich, creamy, and surprisingly healthy dessert that no one will guess is made with avocados!\n\n### Ingredients\n* 2 large ripe avocados\n* 1/4 cup unsweetened cocoa powder\n* 1/4 cup maple syrup or agave nectar\n* 2 tbsp almond milk (or any plant milk)\n* 1 tsp vanilla extract\n* 1/4 tsp salt\n* Fresh berries for garnish\n\n### Instructions\n1. Cut avocados in half, remove pits, and scoop flesh into a food processor.\n2. Add cocoa powder, maple syrup, almond milk, vanilla, and salt.\n3. Process until completely smooth and creamy, scraping down sides as needed.\n4. Taste and adjust sweetness if needed.\n5. Divide into serving bowls and refrigerate for at least 2 hours.\n6. Serve chilled, garnished with fresh berries.\n\n### Notes\n* Make sure avocados are very ripe for the best texture\n* This mousse will keep in the refrigerator for up to 3 days\n* You can substitute the maple syrup with dates for a refined sugar-free option"
  },
  {
    "id": "trace_003",
    "input": "Quick 15-minute dinner ideas",
    "output": "## Garlic Butter Shrimp Pasta\n\nA restaurant-quality dish that comes together in just 15 minutes with simple ingredients.\n\n### Ingredients\n* 8 oz linguine or spaghetti\n* 1 lb large shrimp, peeled and deveined\n* 4 cloves garlic, minced\n* 4 tbsp butter\n* 2 tbsp olive oil\n* 1/4 cup white wine (optional)\n* 2 tbsp fresh lemon juice\n* 1/4 cup fresh parsley, chopped\n* Red pepper flakes to taste\n* Salt and black pepper\n* Parmesan cheese for serving\n\n### Instructions\n1. Cook pasta according to package directions while preparing shrimp.\n2. Heat olive oil in a large skillet over medium-high heat.\n3. Season shrimp with salt and pepper, add to skillet.\n4. Cook shrimp 2-3 minutes per side until pink, then remove.\n5. Add butter and garlic to the same pan, cook 30 seconds.\n6. Add wine (if using) and lemon juice, simmer 1 minute.\n7. Return shrimp to pan, add drained pasta and parsley.\n8. Toss everything together and serve with Parmesan.\n\n### Tips\n* Don't overcook the shrimp - they cook very quickly\n* Reserve some pasta water to help bind the sauce if needed"
  },
  {
    "id": "trace_004",
    "input": "What's a good breakfast for someone with gluten intolerance?",
    "output": "## Fluffy Gluten-Free Pancakes\n\nLight, fluffy pancakes that taste just as good as traditional ones, perfect for a weekend breakfast.\n\n### Ingredients\n* 1 cup gluten-free flour blend (with xanthan gum)\n* 2 tbsp sugar\n* 2 tsp baking powder\n* 1/2 tsp salt\n* 1 cup milk\n* 1 large egg\n* 2 tbsp melted butter\n* 1 tsp vanilla extract\n* Butter or oil for cooking\n\n### Instructions\n1. In a large bowl, whisk together flour, sugar, baking powder, and salt.\n2. In another bowl, combine milk, egg, melted butter, and vanilla.\n3. Pour wet ingredients into dry ingredients and stir until just combined (don't overmix).\n4. Heat a non-stick pan or griddle over medium heat and lightly grease.\n5. Pour 1/4 cup batter for each pancake onto the hot surface.\n6. Cook until bubbles form on surface and edges look set, about 2-3 minutes.\n7. Flip and cook another 1-2 minutes until golden brown.\n8. Serve hot with maple syrup, fresh fruit, or your favorite toppings.\n\n### Notes\n* Make sure your flour blend contains xanthan gum for the best texture\n* Let the batter rest for 5 minutes before cooking for even fluffier pancakes"
  },
  {
    "id": "trace_005",
    "input": "I have leftover turkey from Thanksgiving",
    "output": "## Turkey and Cranberry Grilled Sandwich\n\nA delicious way to transform Thanksgiving leftovers into a gourmet sandwich that celebrates those classic flavors.\n\n### Ingredients\n* 8 slices sourdough or whole grain bread\n* 2 cups leftover turkey, sliced or shredded\n* 4 oz cream cheese, softened\n* 1/4 cup cranberry sauce\n* 1/2 cup baby spinach or arugula\n* 4 slices brie or swiss cheese\n* 2 tbsp butter\n* Salt and pepper to taste\n\n### Instructions\n1. Mix cream cheese with 2 tablespoons of cranberry sauce until smooth.\n2. Spread the cranberry cream cheese mixture on 4 slices of bread.\n3. Layer turkey, cheese, remaining cranberry sauce, and greens on top.\n4. Top with remaining bread slices.\n5. Butter the outside of each sandwich.\n6. Heat a large skillet over medium heat.\n7. Cook sandwiches 3-4 minutes per side until golden brown and cheese is melted.\n8. Cut diagonally and serve hot.\n\n### Variations\n* Add sliced apples for extra crunch and sweetness\n* Use stuffing instead of bread for an extra indulgent twist\n* Try it with leftover gravy as a dipping sauce"
  },
  {
    "id": "trace_006",
    "input": "Healthy snack for kids",
    "output": "## Apple Nachos with Peanut Butter Drizzle\n\nA fun, healthy twist on nachos that kids will love - crispy apple slices topped with delicious and nutritious toppings.\n\n### Ingredients\n* 2 large apples (Honeycrisp or Gala work well)\n* 3 tbsp natural peanut butter\n* 1 tbsp honey\n* 1-2 tbsp milk (to thin)\n* 2 tbsp mini chocolate chips\n* 2 tbsp chopped nuts (optional, omit for nut allergies)\n* 1 tbsp shredded coconut\n* 1 tbsp dried cranberries or raisins\n\n### Instructions\n1. Wash and core apples, then slice into thin wedges.\n2. Arrange apple slices on a large plate, overlapping slightly like nachos.\n3. In a small bowl, mix peanut butter, honey, and milk until smooth and drizzleable.\n4. Drizzle the peanut butter mixture over the apple slices.\n5. Sprinkle with chocolate chips, nuts, coconut, and dried fruit.\n6. Serve immediately for the best texture.\n\n### Tips\n* To prevent browning, lightly brush apple slices with lemon juice\n* For nut-free version, substitute peanut butter with sunflower seed butter\n* Let kids choose their own toppings for a fun interactive snack"
  },
  {
    "id": "trace_007",
    "input": "What's a good soup for cold weather?",
    "output": "## Hearty Beef and Vegetable Stew\n\nA warming, stick-to-your-ribs stew perfect for cold days, packed with tender beef and hearty vegetables.\n\n### Ingredients\n* 2 lbs beef chuck roast, cut into 2-inch cubes\n* 3 tbsp vegetable oil\n* 1 large onion, diced\n* 3 carrots, sliced\n* 3 celery stalks, chopped\n* 3 cloves garlic, minced\n* 3 tbsp tomato paste\n* 1/4 cup flour\n* 4 cups beef broth\n* 1 cup red wine (optional)\n* 1 lb potatoes, cubed\n* 2 bay leaves\n* 1 tsp dried thyme\n* Salt and pepper to taste\n* Fresh parsley for garnish\n\n### Instructions\n1. Season beef cubes with salt and pepper, then toss with flour.\n2. Heat oil in a large Dutch oven over medium-high heat.\n3. Brown beef on all sides, working in batches. Remove and set aside.\n4. Add onion, carrots, and celery to the pot, cook 5 minutes.\n5. Add garlic and tomato paste, cook 1 minute more.\n6. Return beef to pot, add broth, wine, bay leaves, and thyme.\n7. Bring to a boil, then reduce heat and simmer covered for 1.5 hours.\n8. Add potatoes and cook 30 minutes more until beef is tender.\n9. Remove bay leaves, adjust seasoning, and garnish with parsley.\n\n### Notes\n* This stew tastes even better the next day as flavors develop\n* Serve with crusty bread for dipping"
  },
  {
    "id": "trace_008",
    "input": "I want to make pasta but I'm lactose intolerant",
    "output": "## Lemon Garlic Pasta with Herbs\n\nA bright, flavorful pasta dish that's naturally dairy-free and comes together quickly with simple ingredients.\n\n### Ingredients\n* 1 lb spaghetti or linguine\n* 1/3 cup extra virgin olive oil\n* 6 cloves garlic, thinly sliced\n* 1/4 tsp red pepper flakes\n* Zest and juice of 2 large lemons\n* 1/2 cup fresh parsley, chopped\n* 1/4 cup fresh basil, chopped\n* Salt and black pepper to taste\n* Nutritional yeast for serving (optional)\n\n### Instructions\n1. Cook pasta according to package directions until al dente, reserve 1 cup pasta water.\n2. While pasta cooks, heat olive oil in a large skillet over medium heat.\n3. Add sliced garlic and red pepper flakes, cook until garlic is golden, about 2-3 minutes.\n4. Add drained pasta to the skillet with garlic oil.\n5. Add lemon zest, lemon juice, and 1/2 cup pasta water.\n6. Toss vigorously to create a light sauce, adding more pasta water if needed.\n7. Remove from heat and stir in fresh herbs.\n8. Season with salt and pepper, serve with nutritional yeast if desired.\n\n### Variations\n* Add cherry tomatoes and olives for a Mediterranean twist\n* Toss in some roasted vegetables like zucchini or bell peppers\n* Use dairy-free parmesan alternative for extra richness"
  },
  {
    "id": "trace_009",
    "input": "Mexican food recipes",
    "output": "## Chicken Tacos with Cilantro Lime Crema\n\nAuthentic-tasting chicken tacos with a zesty crema that brings together fresh Mexican flavors in every bite.\n\n### Ingredients\n* 1.5 lbs boneless chicken thighs\n* 2 tsp chili powder\n* 1 tsp cumin\n* 1 tsp paprika\n* 1/2 tsp garlic powder\n* 1/2 tsp oregano\n* Salt and pepper to taste\n* 2 tbsp olive oil\n* 8 corn tortillas\n* 1/2 cup sour cream\n* Juice of 1 lime\n* 1/4 cup fresh cilantro, chopped\n* 1/2 red onion, diced\n* 1 avocado, sliced\n* Lime wedges for serving\n\n### Instructions\n1. Mix chili powder, cumin, paprika, garlic powder, oregano, salt, and pepper.\n2. Season chicken thighs with the spice mixture.\n3. Heat olive oil in a large skillet over medium-high heat.\n4. Cook chicken 6-7 minutes per side until cooked through.\n5. Let rest 5 minutes, then slice into strips.\n6. Meanwhile, mix sour cream, lime juice, and half the cilantro for crema.\n7. Warm tortillas in a dry skillet or over open flame.\n8. Fill tortillas with chicken, top with crema, onion, avocado, and remaining cilantro.\n9. Serve with lime wedges.\n\n### Tips\n* For extra flavor, marinate chicken in spices for 30 minutes before cooking\n* Try adding pickled jalapeños or hot sauce for heat"
  },
  {
    "id": "trace_010",
    "input": "I'm cooking for someone with a nut allergy",
    "output": "## Nut-Free Chicken Parmesan\n\nA classic comfort food dish that's completely nut-free and safe for those with allergies, without compromising on flavor.\n\n### Ingredients\n* 4 boneless, skinless chicken breasts\n* 1 cup all-purpose flour\n* 2 large eggs, beaten\n* 2 cups panko breadcrumbs\n* 1/2 cup grated Parmesan cheese\n* 1 tsp Italian seasoning\n* 1/2 tsp garlic powder\n* Salt and pepper to taste\n* 1/4 cup vegetable oil\n* 2 cups marinara sauce\n* 1 cup mozzarella cheese, shredded\n* Fresh basil for garnish\n\n### Instructions\n1. Preheat oven to 425°F (220°C).\n2. Pound chicken to 1/2-inch thickness and season with salt and pepper.\n3. Set up breading station: flour in one dish, beaten eggs in another.\n4. Mix panko, Parmesan, Italian seasoning, and garlic powder in third dish.\n5. Dredge each chicken breast in flour, then egg, then breadcrumb mixture.\n6. Heat oil in large oven-safe skillet over medium-high heat.\n7. Cook chicken 3-4 minutes per side until golden brown.\n8. Top each piece with marinara sauce and mozzarella cheese.\n9. Transfer skillet to oven and bake 15-20 minutes until cheese is bubbly.\n10. Garnish with fresh basil and serve.\n\n### Safety Notes\n* Always check that all ingredients are processed in nut-free facilities\n* This recipe uses no nuts or nut-derived ingredients"
  },
  {
    "id": "trace_011",
    "input": "What can I bake for a beginner?",
    "output": "## Simple Chocolate Chip Cookies\n\nPerfect for baking beginners - these cookies are nearly foolproof and turn out soft, chewy, and delicious every time.\n\n### Ingredients\n* 2 1/4 cups all-purpose flour\n* 1 tsp baking soda\n* 1 tsp salt\n* 1 cup butter, softened\n* 3/4 cup granulated sugar\n* 3/4 cup brown sugar, packed\n* 2 large eggs\n* 2 tsp vanilla extract\n* 2 cups chocolate chips\n\n### Instructions\n1. Preheat oven to 375°F (190°C).\n2. In a medium bowl, whisk together flour, baking soda, and salt.\n3. In a large bowl, cream together softened butter and both sugars until light and fluffy.\n4. Beat in eggs one at a time, then add vanilla.\n5. Gradually mix in the flour mixture until just combined.\n6. Stir in chocolate chips.\n7. Drop rounded tablespoons of dough onto ungreased baking sheets, spacing 2 inches apart.\n8. Bake 9-11 minutes until edges are lightly golden (centers may look slightly underbaked).\n9. Cool on baking sheet for 5 minutes before transferring to wire rack.\n\n### Beginner Tips\n* Make sure butter is room temperature - it should give slightly when pressed\n* Don't overmix the dough once you add flour\n* Cookies will look slightly underbaked when done - they'll finish cooking on the hot pan"
  },
  {
    "id": "trace_012",
    "input": "Asian fusion dinner ideas",
    "output": "## Korean BBQ Beef Bowls\n\nA fusion dish that combines Korean flavors with the convenience of a rice bowl, perfect for busy weeknights.\n\n### Ingredients\n* 1 lb thinly sliced ribeye or sirloin\n* 1/3 cup soy sauce\n* 2 tbsp brown sugar\n* 2 tbsp sesame oil\n* 4 cloves garlic, minced\n* 1 tbsp fresh ginger, grated\n* 2 tsp gochujang (Korean chili paste)\n* 3 cups cooked jasmine rice\n* 1 cucumber, julienned\n* 2 carrots, julienned\n* 2 tbsp rice vinegar\n* 1 tsp sugar\n* 4 fried eggs\n* 2 green onions, sliced\n* Sesame seeds for garnish\n\n### Instructions\n1. Marinate beef in soy sauce, brown sugar, sesame oil, garlic, ginger, and gochujang for 30 minutes.\n2. Mix cucumber and carrots with rice vinegar and sugar for quick pickle.\n3. Heat a large skillet over high heat and cook marinated beef 2-3 minutes until caramelized.\n4. Fry eggs sunny-side up in another pan.\n5. Divide rice among 4 bowls.\n6. Top with beef, pickled vegetables, and a fried egg.\n7. Garnish with green onions and sesame seeds.\n8. Serve with extra gochujang on the side.\n\n### Notes\n* Freeze beef for 30 minutes before slicing for easier cutting\n* Substitute ground beef if you can't find thinly sliced steak"
  },
  {
    "id": "trace_013",
    "input": "I need something to bring to a potluck",
    "output": "## Classic Potato Salad\n\nA crowd-pleasing side dish that's perfect for potlucks, barbecues, and gatherings - this recipe serves 8-10 people.\n\n### Ingredients\n* 3 lbs red or Yukon potatoes\n* 6 large eggs\n* 3/4 cup mayonnaise\n* 2 tbsp yellow mustard\n* 1 tbsp apple cider vinegar\n* 1 large onion, finely diced\n* 3 celery stalks, diced\n* 1/4 cup fresh dill, chopped\n* 2 tbsp fresh chives, chopped\n* Salt and pepper to taste\n* Paprika for garnish\n\n### Instructions\n1. Wash potatoes and cut into 1-inch cubes (leave skin on).\n2. Boil potatoes in salted water 12-15 minutes until fork-tender but not mushy.\n3. Meanwhile, hard-boil eggs: boil 10 minutes, then ice bath.\n4. Drain potatoes and let cool completely.\n5. Peel and chop eggs.\n6. In a large bowl, whisk together mayo, mustard, and vinegar.\n7. Add cooled potatoes, eggs, onion, celery, and herbs.\n8. Gently fold together, season with salt and pepper.\n9. Refrigerate at least 2 hours before serving.\n10. Garnish with paprika before serving.\n\n### Tips\n* Make this salad the day before for best flavor development\n* Keep chilled until ready to serve for food safety\n* This recipe easily doubles for larger crowds"
  },
  {
    "id": "trace_014",
    "input": "Seafood pasta recipe",
    "output": "## Linguine alle Vongole (Clam Pasta)\n\nA classic Italian seafood pasta that's elegant enough for dinner parties but simple enough for weeknight meals.\n\n### Ingredients\n* 1 lb linguine\n* 2 lbs littleneck clams, scrubbed\n* 1/3 cup extra virgin olive oil\n* 4 cloves garlic, sliced thin\n* 1/2 cup dry white wine\n* 1/4 tsp red pepper flakes\n* 1/4 cup fresh parsley, chopped\n* 2 tbsp butter\n* Juice of 1/2 lemon\n* Salt and black pepper to taste\n\n### Instructions\n1. Soak clams in cold salted water for 20 minutes to remove sand.\n2. Cook linguine according to package directions until al dente, reserve 1 cup pasta water.\n3. Meanwhile, heat olive oil in a large skillet over medium heat.\n4. Add garlic and red pepper flakes, cook until fragrant, about 1 minute.\n5. Add clams and wine, cover and cook 5-8 minutes until clams open.\n6. Discard any clams that don't open.\n7. Add drained pasta to the skillet with clams.\n8. Toss with pasta water as needed to create a light sauce.\n9. Remove from heat, stir in butter, lemon juice, and parsley.\n10. Season with salt and pepper, serve immediately.\n\n### Tips\n* Fresh clams are essential for this dish - avoid canned\n* Don't overcook the clams or they'll become rubbery\n* Serve with crusty bread to soak up the delicious broth"
  },
  {
    "id": "trace_015",
    "input": "What's good for meal prep?",
    "output": "## Mediterranean Chicken Bowls\n\nPerfect for meal prep - these bowls stay fresh for days and are packed with protein, healthy fats, and vegetables.\n\n### Ingredients\n* 2 lbs boneless chicken thighs\n* 2 tbsp olive oil\n* 2 tsp oregano\n* 1 tsp garlic powder\n* 1 tsp lemon zest\n* Salt and pepper to taste\n* 2 cups cooked quinoa\n* 1 cucumber, diced\n* 2 cups cherry tomatoes, halved\n* 1/2 red onion, thinly sliced\n* 1/2 cup kalamata olives\n* 1/2 cup crumbled feta cheese\n* 1/4 cup olive oil\n* 2 tbsp lemon juice\n* 1 tbsp red wine vinegar\n* 1 tsp dried oregano\n* 2 tbsp fresh parsley, chopped\n\n### Instructions\n1. Preheat oven to 425°F (220°C).\n2. Season chicken with olive oil, oregano, garlic powder, lemon zest, salt, and pepper.\n3. Roast chicken 25-30 minutes until cooked through. Let cool and slice.\n4. Meanwhile, prepare quinoa according to package directions and let cool.\n5. Make dressing by whisking together olive oil, lemon juice, vinegar, and oregano.\n6. In meal prep containers, layer quinoa, chicken, cucumber, tomatoes, onion, and olives.\n7. Top with feta and drizzle with dressing (keep separate until serving).\n8. Store in refrigerator up to 4 days.\n\n### Meal Prep Tips\n* Keep dressing separate to prevent soggy vegetables\n* These bowls can be eaten cold or reheated\n* Swap quinoa for rice or farro for variety"
  },
  {
    "id": "trace_016",
    "input": "I want to make bread but I'm scared of yeast",
    "output": "## No-Yeast Irish Soda Bread\n\nA simple, rustic bread that requires no yeast or rising time - perfect for beginners who want fresh homemade bread in under an hour.\n\n### Ingredients\n* 4 cups all-purpose flour\n* 1 tsp salt\n* 1 tsp baking soda\n* 1 3/4 cups buttermilk\n* 1 tbsp honey (optional)\n\n### Instructions\n1. Preheat oven to 425°F (220°C).\n2. In a large bowl, whisk together flour, salt, and baking soda.\n3. Make a well in the center and pour in buttermilk and honey if using.\n4. Using a wooden spoon, stir until a shaggy dough forms - don't overmix.\n5. Turn dough onto a lightly floured surface and gently knead 2-3 times just to bring together.\n6. Shape into a round loaf about 8 inches across.\n7. Place on a parchment-lined baking sheet.\n8. Using a sharp knife, cut a deep X across the top.\n9. Bake 30-35 minutes until golden brown and sounds hollow when tapped.\n10. Cool on a wire rack before slicing.\n\n### Tips\n* Don't overwork the dough or the bread will be tough\n* The X on top isn't just decorative - it helps the bread bake evenly\n* This bread is best eaten the day it's made\n* Try adding raisins or herbs for variation"
  },
  {
    "id": "trace_017",
    "input": "Summer grilling recipes",
    "output": "## Grilled Honey Lime Chicken\n\nJuicy, flavorful chicken with a perfect balance of sweet and tangy flavors that screams summer barbecue.\n\n### Ingredients\n* 4 boneless, skinless chicken breasts\n* 1/4 cup honey\n* 1/4 cup fresh lime juice\n* 2 tbsp olive oil\n* 3 cloves garlic, minced\n* 1 tsp cumin\n* 1 tsp chili powder\n* 1/2 tsp paprika\n* Salt and pepper to taste\n* Lime wedges for serving\n* Fresh cilantro for garnish\n\n### Instructions\n1. Pound chicken to even 3/4-inch thickness.\n2. In a bowl, whisk together honey, lime juice, olive oil, garlic, cumin, chili powder, paprika, salt, and pepper.\n3. Reserve 1/4 cup marinade for basting.\n4. Marinate chicken in remaining mixture for 30 minutes to 4 hours.\n5. Preheat grill to medium-high heat and oil grates.\n6. Remove chicken from marinade and grill 6-7 minutes per side.\n7. Baste with reserved marinade during last few minutes of cooking.\n8. Check internal temperature reaches 165°F (74°C).\n9. Let rest 5 minutes before serving.\n10. Garnish with cilantro and serve with lime wedges.\n\n### Grilling Tips\n* Don't move the chicken too early - let it develop good grill marks\n* If flare-ups occur, move chicken to cooler part of grill\n* This marinade also works great with shrimp or fish"
  },
  {
    "id": "trace_018",
    "input": "Something spicy and warming",
    "output": "## Spicy Three-Bean Chili\n\nA hearty, warming chili with just the right amount of heat to chase away the cold and fill you up.\n\n### Ingredients\n* 1 lb ground beef or turkey\n* 1 large onion, diced\n* 1 bell pepper, diced\n* 4 cloves garlic, minced\n* 2 tbsp chili powder\n* 1 tbsp cumin\n* 1 tsp smoked paprika\n* 1/2 tsp cayenne pepper (adjust to taste)\n* 1 can (28 oz) crushed tomatoes\n* 1 can black beans, drained and rinsed\n* 1 can kidney beans, drained and rinsed\n* 1 can pinto beans, drained and rinsed\n* 2 cups beef broth\n* 1 tbsp tomato paste\n* 1 tsp oregano\n* Salt and pepper to taste\n* Sour cream, cheese, and green onions for serving\n\n### Instructions\n1. Brown ground meat in a large pot over medium-high"
  },
]